version: '3'

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6375:6375

  cache_sync:
    environment:
      CACHE_ENV: "docker"
    build:
      context: ./cache_sync
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./storage:/opt/cache_sync/storage

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 8000:8000

  dynamodb_setup:
    build:
      context: ./dynamodb
      dockerfile: Dockerfile
    depends_on:
      - dynamodb

  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    volumes:
      - ./kafka/kafka-logs:/tmp/kafka-logs
      - ./kafka/zookeeper:/var/lib/zookeeper

  kafka_setup:
    environment:
      CACHE_ENV: "docker"
    build:
      context: ./kafka
      dockerfile: Dockerfile
    depends_on:
      - kafka

  koa:
    depends_on:
      - dynamodb
    image: node:10
    ports:
      - 3000:3000
    volumes:
      - ./koa-service:/opt/koa-service
    command: ["node", "/opt/koa-service/server.js"]

