version: '3'

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6375:6375

  cache_sync:
    build:
      context: ./cache_sync
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./storage:/opt/cache_sync/storage
      - ./mount/app/utils:/opt/cache_sync/app/utils
      - ./mount/config:/opt/cache_sync/config

  watch_reviews:
    build:
      context: ./watch-reviews
      dockerfile: Dockerfile
    depends_on:
      - redis
      - queue_setup
      - dynamodb_setup
    volumes:
      - ./storage:/opt/watch_reviews/storage
      - ./mount/app/utils:/opt/watch_reviews/app/utils
      - ./mount/config:/opt/watch_reviews/config

  process_queue:
    build:
      context: ./process-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
      - queue_setup
      - dynamodb_setup
    volumes:
      - ./storage:/opt/process_queue/storage
      - ./mount/app/utils:/opt/process_queue/app/utils
      - ./mount/config:/opt/process_queue/config

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

  dynamodb_setup:
    build:
      context: ./dynamodb_setup
      dockerfile: Dockerfile
    depends_on:
      - dynamodb
    volumes:
      - ./mount/app/utils:/opt/dynamodb_setup/app/utils
      - ./mount/config:/opt/dynamodb_setup/config

  kafka:
    environment:
      ADVERTISED_HOST: "kafka"
      ADVERTISED_PORT: 9092
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    volumes:
      - ../storage/kafka/kafka-logs:/tmp/kafka-logs
      - ../storage/kafka/zookeeper:/var/lib/zookeeper

  queue_setup:
    build:
      context: ./queue_setup
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./mount/app/utils:/opt/queue_setup/app/utils
      - ./mount/config:/opt/queue_setup/config

  koa:
    command: ["node", "/opt/koa-service/app/server.js"]
    depends_on:
      - cache_sync
      - watch_reviews
      - process_queue
      - vanilla
    image: node:12
    ports:
      - 3000:3000
    volumes:
      - ./koa-service:/opt/koa-service
    working_dir: /opt/koa-service

  vanilla:
    command: ["node", "/opt/vanilla/app/server.js"]
    image: node:12
    ports:
      - 3001:3001
    volumes:
      - ./fe/vanilla:/opt/vanilla
    working_dir: /opt/vanilla

