version: '3'

services:
  bond-movies-api:
    build:
      context: ./bond-movies-api
      dockerfile: ./Dockerfile
    depends_on:
      - dynamodb
    ports:
      - 3000:3000
    working_dir: /opt/bond-movies-api

  bond-movies-api-spring:
    build:
      context: ./BondSpring
      dockerfile: ./src/main/resources/docker/Dockerfile
    depends_on:
      - dynamodb
    ports:
      - 3009:8080
    working_dir: /

  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    container_name: dynamodb
    entrypoint: java
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - ./storage/dynamodb-data:/data

  kafka:
    environment:
      ADVERTISED_HOST: "kafka"
      ADVERTISED_PORT: 9092
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    volumes:
      - ./storage/kafka/kafka-logs:/tmp/kafka-logs
      - ./storage/kafka/zookeeper:/var/lib/zookeeper

  omdb-api:
    build:
      context: ./omdb-api
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 3001:3001
    volumes:
      - ./storage:/opt/cache_sync/storage
      - ./mount/app/utils:/opt/cache_sync/app/utils
      - ./mount/config:/opt/cache_sync/config

  process-queue:
    build:
      context: ./process-queue
      dockerfile: Dockerfile
    depends_on:
      - kafka
    container_name: "process_queue"
    ports:
      - 3002:3002

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6375:6375

  vanilla:
    image: nginx
    ports:
      - 9090:80
    volumes:
      - ./fe/vanilla/public:/usr/share/nginx/html:ro

  watch-reviews:
    build:
      context: ./watch-reviews
      dockerfile: Dockerfile
    container_name: "watch_reviews"
    volumes:
      - ./watch-reviews/storage:/opt/watch_reviews/storage

