version: '3'

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 8000:8000

  dynamodb_setup:
    build:
      context: ./dynamodb
      dockerfile: Dockerfile
    depends_on:
      - dynamodb

