version: '3'

services:
  bond-movies-api:
    build:
      context: ./bond-movies-api
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    working_dir: /opt/bond-movies-api

  omdb-api:
    build:
      context: ./omdb-api
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 3001:3001
    volumes:
      - ./storage:/opt/cache_sync/storage
      - ./mount/app/utils:/opt/cache_sync/app/utils
      - ./mount/config:/opt/cache_sync/config

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

  kafka:
    environment:
      ADVERTISED_HOST: "kafka"
      ADVERTISED_PORT: 9092
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    volumes:
      - ../storage/kafka/kafka-logs:/tmp/kafka-logs
      - ../storage/kafka/zookeeper:/var/lib/zookeeper

  process_queue:
    build:
      context: ./process-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
      - queue_setup
    volumes:
      - ./storage:/opt/process_queue/storage
      - ./mount/app/utils:/opt/process_queue/app/utils
      - ./mount/config:/opt/process_queue/config

  queue_setup:
    build:
      context: ./queue_setup
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./mount/app/utils:/opt/queue_setup/app/utils
      - ./mount/config:/opt/queue_setup/config

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6375:6375

  vanilla:
    command: ["node", "/opt/vanilla/app/server.js"]
    image: node:12
    ports:
      - 3001:3001
    volumes:
      - ./fe/vanilla:/opt/vanilla
    working_dir: /opt/vanilla

  watch_reviews:
    build:
      context: ./watch-reviews
      dockerfile: Dockerfile
    depends_on:
      - redis
      - queue_setup
    volumes:
      - ./storage:/opt/watch_reviews/storage
      - ./mount/app/utils:/opt/watch_reviews/app/utils
      - ./mount/config:/opt/watch_reviews/config

