version: '3'

services:
  redis:
    environment:
      CACHE_ENV: "docker"
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6375:6375

  cache_sync:
    build:
      context: ./cache_sync
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./storage:/opt/cache_sync/storage

  watch_reviews:
    environment:
      CACHE_ENV: "docker"
    build:
      context: ./watch-reviews
      dockerfile: Dockerfile
    depends_on:
      - redis
      - kafka_setup
      - dynamodb_setup
    volumes:
      - ./storage:/opt/watch_reviews/storage

  process_queue:
    build:
      context: ./process-queue
      dockerfile: Dockerfile
    ports:
      - "9229:9229"
    depends_on:
      - redis
      - kafka_setup
      - dynamodb_setup
    volumes:
      - ./storage:/opt/process_queue/storage

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 8000:8000

  dynamodb_setup:
    build:
      context: ./dynamodb
      dockerfile: Dockerfile
    depends_on:
      - dynamodb

  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: "kafka"
      ADVERTISED_PORT: 9092
    volumes:
      - ./kafka/kafka-logs:/tmp/kafka-logs
      - ./kafka/zookeeper:/var/lib/zookeeper

  kafka_setup:
    environment:
      CACHE_ENV: "docker"
    build:
      context: ./queue_setup
      dockerfile: Dockerfile
    depends_on:
      - kafka

  koa:
    command: ["node", "/opt/koa-service/app/server.js"]
    depends_on:
      - cache_sync
      - watch_reviews
      - process_queue
      - vanilla
    image: node:12
    ports:
      - 3000:3000
    volumes:
      - ./koa-service:/opt/koa-service
    working_dir: /opt/koa-service
  
  vanilla:
    command: ["node", "/opt/vanilla/app/server.js"]
    image: node:12
    ports:
      - 3001:3001
    volumes:
      - ./fe/vanilla:/opt/vanilla
    working_dir: /opt/vanilla

