package org.troot.BondSpring.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@DynamoDBTable(tableName = "BondMovies")
public class BondMovie {

  private String MovieTitle;
  private String Title;

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  @Id
  public String getMovieTitle() {
    return MovieTitle;
  }
  public void setMovieTitle(String newMovieTitle) {
    MovieTitle = newMovieTitle;
  }

  @DynamoDBAttribute
  public String getTitle() {
    return Title;
  }
  public void setTitle(String newTitle) {
    Title = newTitle;
  }

  public BondMovie() {
    super();
  }

}
