package org.troot.BondSpring.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
@DynamoDBTable(tableName = "BondMovies")
public class BondMovie {

  @Id
  private String title;
  @DynamoDBHashKey(attributeName = "title")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  private String Actors;
  @DynamoDBAttribute(attributeName = "Actors")
  public String getActors() {
    return Actors;
  }

  public BondMovie() {
    super();
  }

  public BondMovie(String movieTitle, String title) {
    super();
    this.title = title;
  }
}
