package org.troot.BondSpring.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
@DynamoDBTable(tableName = "BondMovies")
public class BondMovie {

  @Id
  private String MovieTitle;
  @DynamoDBHashKey(attributeName = "MovieTitle")
  public String getMovieTitle() {
    return MovieTitle;
  }
  public void setMovieTitle(String MovieTitle) {
    this.MovieTitle = MovieTitle;
  }

  @DynamoDBAttribute(attributeName = "Title")
  private String Title;
  public String getTitle() {
    return Title;
  }
  public void setTitle(String Title) {
    this.Title = Title;
  }

  public BondMovie() {
    super();
  }

  public BondMovie(String movieTitle, String title) {
    super();
    this.MovieTitle = movieTitle;
    this.Title = title;
  }
}
